# Generated by Django 5.2.7 on 2025-11-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleApi', '0002_alter_menuitem_inventory_alter_user_groups_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('closed', 'livré'), ('open', 'non livré'), ('cancelled', 'annulé')], default='open', max_length=100),
        ),
    ]
