# Generated by Django 5.2.7 on 2025-11-20 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleApi', '0003_alter_cart_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('open', 'non livré'), ('cancelled', 'annulé'), ('closed', 'livré')], default='open', max_length=100),
        ),
    ]
